version: '3'

services:
 
 frontend:
  build:
   dockerfile: ./gs-serving-web-content/Dockerfile
  depends_on:
   - backend
 backend:
  build:
   dockerfile: ./skills-manager/Dockerfile
   ports:
    - "80:8080"